@startuml activity_diagram

(*)-->"Create an array for phase space density"
note right:like this array[x1(t),x1(t-Δt),x2(t),x2(t-Δt),x3(t),x3(t-Δt)...]

-->"Substitute the initial value"

-->""



-->(*)

@end uml
